name: earth-analytics-neon
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.8
  - pip=22.0.4
  # Core scientific python
  - numpy=1.22.3
  - pyqt
  - tqdm=4.63.1
  - kiwisolver=1.4.2

  # Plotting
  - matplotlib=3.5.1
  - plotly=5.6.0
  - seaborn=0.11.2

  # Spatial packages
  - pysal=2.6.0
  - pyproj>=3.0
  - rasterstats=0.16.0
  - geopy=2.2.0
  - cartopy=0.20.2
  - descartes=1.1.0
  - contextily=1.2.0
  - earthpy=0.9.4
  - folium=0.12
  - geojson=2.5.0
  - mapboxgl=0.10.2
  - hydrofunctions=0.2.1
  - geocoder=1.38.1
  - tweepy=4.8.0
  - xarray=2022.3.0
  - rioxarray>=0.3.0
  - scipy=1.8.0
  - netcdf4=1.5.8
  - nc-time-axis=1.4.0
  - regionmask=0.9.0
  - h5py=3.6.0

  # Natural language processing
  - nltk=3.6.7
  - textblob=0.15.3

  # Jupyter Environment
  - papermill=2.3.4
  - autopep8=1.6.0
  - jupyterlab=3.3.2
  - notebook=6.4.10
  - ipython=8.2.0
  - jupyter_contrib_nbextensions=0.5.1
  - nbclean=0.1
  - nbresuse=0.4.0

  # Autograding
  - matplotcheck>=0.1.3
  - nbgrader=0.6.2
